### ISSUE TITLE
ta library issue

### ISSUE THREAD

**Issue by DavidLanz** [bukosabino/btctrading#14]
try to run XGBoost, have download ta library, but encounter issue here:

1. name 'acc_dist_roc' is not defined
2. acc_dist_index() missing 2 required positional arguments: 'close' and 'volume'

df['Acc_Dist_Roc_BTC'] = acc_dist_roc(df, 'Volume_BTC', 2)
df['Acc_Dist_Roc_Currency'] = acc_dist_roc(df, 'Volume_Currency', 2)
df['Acc_Dist_BTC'] = acc_dist_index(df, 'Volume_BTC')
df['Acc_Dist_Currency'] = acc_dist_index(df, 'Volume_Currency')

please advice, thanks!

**Comment by bukosabino** [comment]
Hi, it repository was in an unstable state, sorry.

Now you can use it. We are using a new technical analysis to do feature engineering:
https://github.com/bukosabino/ta

Let me know if you have any problem.
