### ISSUE TITLE
shift problem

### ISSUE THREAD

**Issue by hlsc** [bukosabino/btctrading#6]
# shift
cols = ['Open', 'High', 'Low', 'Close', 'Volume_BTC', 'Volume_Currency', 'Weighted_Price', 'High-low', 'High-low_mean', 'Close-open', 'Close-open_mean', 'Daily_return', 'Daily_return_100', 'Cumulative_return', 'Cumulative_return_100']
for col in cols:
    df[col] = df[col].shift(-1)
df = df.dropna()

why is df[col].shift(-1) not df[col].shift(1)?

**Comment by bukosabino** [comment]
Yeah, you are right. The results were wrong ;(
Fixed now!
