### ISSUE TITLE
Run via CLI?

### ISSUE THREAD

**Issue by imkane** [bukosabino/btctrading#9]
Thanks for this project, looks great!

Is there a way to run this only from Linux CLI?

I'm seeing:
`[W 17:23:08.101 NotebookApp] No web browser found: could not locate runnable browser.`

**Comment by bukosabino** [comment]
Hi @imkane ,

You can copy & paste the code in the ipynb file: https://github.com/bukosabino/btctrading/blob/master/XGBoost.ipynb
in a new file python, xgboost.py for example.

Then you run with:

> python xgboost.py

**Comment by imkane** [comment]
Thank you! I'm new to Python :(

FYI for any other newbies, I ran:
`jupyter nbconvert --to script 'XGBoost.ipynb'`

To convert the JSON notebook file to a Python script.
